### ISSUE TITLE
Last batch of 4 paper wallets gets pushed off the page

### ISSUE THREAD

**Issue by IfaqYurmama** [NAVCoin/paper-wallet#6]
![unknown](https://user-images.githubusercontent.com/33290035/36584206-0a9c7806-1879-11e8-8228-03f481d9b6ea.png)

The button "Test Encryption" is printed on the page and pushes the last address off the page onto the next one

**Comment by matt-auckland** [comment]
Out of curiosity, what browser and OS are you using?

**Comment by IfaqYurmama** [comment]
I used Windows 10 in this case, haven't tried with any other system so far.

**Comment by matt-auckland** [comment]
Closing as I've fixed the issue for the next version
